'''
Planck-lite-py example usage for Planck 2018 likelihoods
to use 2015 data, replace year=2018 with year=2015 when creating a PlanckLitePy object
'''
import numpy as np
from planck_lite_py import PlanckLitePy


print('- - - - - - - - - - - - - - - - - - -')
print('Testing Planck-lite-py for 2018 data')
print('- - - - - - - - - - - - - - - - - - -\n')

print('Reading in theory power spectrum (generated by CLASS)\n')
# read some spectra to pass to the likelihood (can use CAMB/CLASS to generate these)
ls, Dltt, Dlte, Dlee = np.genfromtxt('data/Dl_planck2015fit.dat', unpack=True)
ellmin=int(ls[0])


print('Test 1: high-l (l>=30) temperature only (TT)')
print('- - - - - - - - - - - - - - - - - - - - - -')
# create a PlanckLitePy object
TT2018=PlanckLitePy(data_directory='data', year=2018, spectra='TT', use_low_ell_bins=False)

# call the likelihood function
loglike=TT2018.loglike(Dltt, Dlte, Dlee, ellmin)
expected=-101.58123068722583
print('Planck-lite-py log likelihood:', loglike)
print('Expected log likelihood:', expected)
print('Difference:', loglike-expected, '\n\n')


print('Test 2: high-l (l>=30) TT, TE and EE data + low-l TT bins')
print('- - - - - - - - - - - - - - - - - - - - - - - - - - - - -')
# create a PlanckLitePy object
TTTEEE2018_lowTTbins=PlanckLitePy(data_directory='data', year=2018, spectra='TTTEEE', use_low_ell_bins=True)

# call the likelihood function
loglike=TTTEEE2018_lowTTbins.loglike(Dltt, Dlte, Dlee, ellmin) #ellmin = 2 by default
expected=-293.95586501795134
print('Planck-lite-py likelihood:', loglike)
print('Expected log likelihood:', expected)
print('Difference:', loglike-expected, '\n\n')
